<?php
/**
 * 某些application会用到钩子
 * 钩子会被挂载到特定的系统执行节点，并根据router信息进行匹配
 * 匹配到的钩子会根据file信息调用，执行action方法
 * {
 *     '格式':{
 *         'file':{
 *             '描述':'文件名，位于hooks文件夹下（同时也是类名）',
 *             '必须':'是'
 *         },
 *         'action':{
 *             '描述':'调用该hook执行方法，默认为run',
 *             '必须':'否'
 *         },
 *         'router':{
 *             '描述':'用于匹配路由的正则，若不设置，所有请求都将执行此hook（特殊hook除外）',
 *             '必须':'否'
 *         }
 *     },
 *     '锚点位置说明':{
 *         'after_controller_constructor':{
 *             '执行时间':'Controller被实例化之后执行',
 *             '传入参数':{}
 *         },
 *         'before_post_create':{
 *             '执行时间':'创建文章之前',
 *             '传入参数':{
 *                 cat_id:'分类ID'
 *             }
 *         },
 *         'after_post_created':{
 *             '执行时间':'创建文章之后',
 *             '传入参数':{
 *                 post_id:'文章ID'
 *             }
 *         },
 *         'before_post_update':{
 *             '执行时间':'编辑文章之前（如果有post提交的话，实际上是完成文章更新之后执行）',
 *             '传入参数':{
 *                 post_id:'文章ID',
 *                 cat_id:'分类ID'
 *             }
 *         },
 *         'after_post_updated':{
 *             '执行时间':'文章更新之后',
 *             '传入参数':{
 *                 post_id:'文章ID'
 *             }
 *         }
 *     }
 * }
 */
return array();